title: Midwest Ale Works (MAW)
url: "https://maw.beer"
baseurl: 
google_analytics_key: UA-164658338-1
google_maps_javascript_api_key:

description: we Work to make Ales for the Midwest

timezone:

paginate:
paginate_path:
permalink: pretty

include: ['_pages']
collections:
  

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag