title: Empower Tanzania
url: "https://empowertz.org"
baseurl:
google_analytics_key: UA-134272490-1
google_maps_javascript_api_key:
_options:
  image: # Front matter field
    uploads_dir: "assets/images/post-images/"
  content: # Content Editor and block Editable Regions
    uploads_dir: "uploads/:year/:month/:day/:title"

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/site-image.png

description: "Empower Tanzania works in partnership with rural Tanzanians to improve their quality of life. We address the underlying issues that hinder resiliency in rural areas, such as health care, education, agriculture practices, markets for products, and increasing water supply and quality."

timezone:

paginate:
paginate_path:
permalink: pretty

include: ['_pages']
collections:
  health_programs:
  education_programs:
  development_programs:
  covid19_responses:

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
