title: Midwest Ale Works (MAW)
url:
baseurl:
google_analytics_key:
google_maps_javascript_api_key:

description:

timezone:

paginate:
paginate_path:
permalink: pretty

include: ['_pages']
collections:
  

# Build settings
markdown: kramdown
plugins:
