title: FIT Rx
url: "https://fitrx-iowa.com"
baseurl: ""
google_analytics_key:

description: Using a functional fitness approach that promotes better movement, increases strength and cardiovascular ability, we provide a well rounded approach to Fitness.

timezone: America/Chicago

paginate:
paginate_path:
permalink: pretty

include: ['_pages']
collections:
  events:
  popups:
  inperson:
  virtual:
  recipes:
  
google_maps_javascript_api_key: "AIzaSyAezwk1m90Wsq_wj9SDQ7nh_-4x7fHAgcs"
# Build settings
markdown: kramdown
plugins:
