title: Empower Tanzania
url:
baseurl:
google_analytics_key:
google_maps_javascript_api_key:

description:

timezone:

paginate:
paginate_path:
permalink: pretty

include: ['_pages']

# Build settings
markdown: kramdown
plugins:
