title: FIT Rx
url: "https://fitrx-iowa.com"
baseurl: ""
google_analytics_key:

description: Using a functional fitness approach that promotes better movement, increases strength and cardiovascular ability, we provide a well rounded approach to Fitness.

timezone:

paginate:
paginate_path:
permalink: pretty

include: ['_pages']
collections:
  
google_maps_javascript_api_key: "AIzaSyCin0fZLR0qmuxfgzpuHDxcMmMFOvGJvMQ"
# Build settings
markdown: kramdown
plugins:
