title: Empower Tanzania
url:
baseurl:
google_analytics_key: UA-134272490-1
google_maps_javascript_api_key:

description:

timezone:

paginate:
paginate_path:
permalink: pretty

include: ['_pages']
collections:
  health_programs:
  education_programs:
  development_programs:

defaults:
  - scope:
    values:
      _options:
        image:
          upload_dir: "assets/images/post-images"
# Build settings
markdown: kramdown
plugins:
