title: FIT Rx
url:
baseurl:
google_analytics_key:
google_maps_javascript_api_key:

description: Using a functional fitness approach that promotes better movement, increases strength and cardiovascular ability, we provide a well rounded approach to Fitness.

timezone:

paginate:
paginate_path:
permalink: pretty

include: ['_pages']
collections:
  

# Build settings
markdown: kramdown
plugins:
