title: Empower Tanzania
url:
baseurl:
google_analytics_key: UA-134272490-1
google_maps_javascript_api_key:
_options:
  image: # Front matter field
    uploads_dir: "assets/images/post-images/:title"
  content: # Content Editor and block Editable Regions
    uploads_dir: "uploads/:year/:month/:day/:title"
description:

timezone:

paginate:
paginate_path:
permalink: pretty

include: ['_pages']
collections:
  health_programs:
  education_programs:
  development_programs:

# Build settings
markdown: kramdown
plugins:
