title: Blue Bench
url:
baseurl:
google_analytics_key:
google_maps_javascript_api_key:

description: Blue Bench is a creator of mobile web applications and custom home projects. We work with local designers and artisans in the Quad Cities to provide the best solution for your home or business.

timezone:

paginate:
paginate_path:
permalink: pretty

include: ['_pages']
collections:
  

# Build settings
markdown: kramdown
plugins:
